import {useEffect,useMemo,useState} from 'react';
import {Building2,Check,Clock3,Filter,MessageSquareText,Users,X} from 'lucide-react';
import {Alert,AlertDescription,AlertTitle} from '@/components/alert';import {Badge} from '@/components/badge';import {Button} from '@/components/button';import {Card,CardContent,CardHeader,CardTitle} from '@/components/card';import {Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle} from '@/components/dialog';import {Input} from '@/components/input';import {Skeleton} from '@/components/skeleton';import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/table';import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/tabs';
import {CompensationScreen} from '../Compensation/CompensationScreen';import {decideManagerRequest,getManagerContext,getManagerEmployees,getManagerRequests,type ManagerContext,type ManagerEmployee,type ManagerRequest} from '@/services/manager.service';
function date(v?:string){return v?new Intl.DateTimeFormat('vi-VN',{dateStyle:'medium'}).format(new Date(v)):'—'}
export function ManagerDepartmentScreen({apiBase,initialTab='approvals'}:{apiBase:string|null;initialTab?:'approvals'|'evaluations'}){
 const[ctx,setCtx]=useState<ManagerContext|null>(null),[dept,setDept]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!apiBase)return;setLoading(true);getManagerContext(apiBase).then(x=>{setCtx(x);setDept(x.defaultDepartmentId??'')}).catch(e=>setError(e instanceof Error?e.message:'Không thể tải phạm vi quản lý.')).finally(()=>setLoading(false))},[apiBase]);
 if(!apiBase)return <Alert variant="destructive"><AlertDescription>Chưa kết nối được API.</AlertDescription></Alert>;
 if(loading)return <div className="space-y-3"><Skeleton className="h-12"/><Skeleton className="h-72"/></div>;
 if(error)return <Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>;
 if(!ctx?.managedDepartments.length)return <Alert><Building2/><AlertTitle>Chưa được phân công phòng ban</AlertTitle><AlertDescription>Liên hệ HR để được gán phạm vi quản lý.</AlertDescription></Alert>;
 return <div className="space-y-5 pb-20 md:pb-0"><header className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h1 className="text-2xl font-semibold sm:text-3xl">Phòng ban</h1><p className="mt-1 text-sm text-muted-foreground">Phê duyệt yêu cầu và đánh giá KPI nhân sự thuộc phạm vi bạn quản lý.</p></div>{ctx.managedDepartments.length>1&&<label className="grid gap-1 text-sm font-medium">Phòng ban<select className="min-h-11 rounded-lg border bg-background px-3" value={dept} onChange={e=>setDept(e.target.value)}>{ctx.managedDepartments.map(d=><option key={d.id} value={d.id}>{d.code} — {d.name}</option>)}</select></label>}</header><Tabs defaultValue={initialTab}><TabsList className="sticky top-0 z-10 h-11 w-full md:static md:w-fit"><TabsTrigger value="approvals" className="px-4">Phê duyệt</TabsTrigger><TabsTrigger value="evaluations" className="px-4">Đánh giá nhân sự</TabsTrigger></TabsList><TabsContent value="approvals"><ApprovalTab apiBase={apiBase} departmentId={dept}/></TabsContent><TabsContent value="evaluations"><CompensationScreen apiBase={apiBase} kind="kpi-inputs" userRole="DEPARTMENT_MANAGER" departmentId={dept}/></TabsContent></Tabs></div>
}
function ApprovalTab({apiBase,departmentId}:{apiBase:string;departmentId:string}){const[rows,setRows]=useState<ManagerRequest[]>([]),[emps,setEmps]=useState<ManagerEmployee[]>([]),[type,setType]=useState('ALL'),[status,setStatus]=useState('PENDING'),[query,setQuery]=useState(''),[busy,setBusy]=useState(true),[error,setError]=useState(''),[selected,setSelected]=useState<ManagerRequest|null>(null),[rev,setRev]=useState(0);
 useEffect(()=>{let c=false;setBusy(true);setError('');Promise.all([getManagerRequests(apiBase,{departmentId,type,status}),getManagerEmployees(apiBase,departmentId)]).then(([r,e])=>{if(!c){setRows(r);setEmps(e)}}).catch(e=>{if(!c)setError(e instanceof Error?e.message:'Không thể tải yêu cầu.')}).finally(()=>{if(!c)setBusy(false)});return()=>{c=true}},[apiBase,departmentId,type,status,rev]);const names=useMemo(()=>new Map(emps.map(e=>[e.id,`${e.employeeCode} — ${e.fullName??'Chưa cập nhật'}`])),[emps]);const shown=rows.filter(r=>`${names.get(r.employeeId)??''} ${r.reason}`.toLowerCase().includes(query.toLowerCase()));
 return <div className="mt-4 space-y-4"><div className="grid gap-3 rounded-xl border bg-card p-4 sm:grid-cols-[1fr_180px_200px_auto]"><Input aria-label="Tìm yêu cầu" placeholder="Tìm nhân viên hoặc lý do…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Loại yêu cầu" className="min-h-11 rounded-lg border bg-background px-3" value={type} onChange={e=>setType(e.target.value)}><option value="ALL">Tất cả loại</option><option value="ATTENDANCE">Công</option><option value="OVERTIME">OT</option></select><select aria-label="Trạng thái" className="min-h-11 rounded-lg border bg-background px-3" value={status} onChange={e=>setStatus(e.target.value)}><option value="PENDING">Chờ duyệt</option><option value="APPROVED">Đã duyệt</option><option value="REJECTED">Từ chối</option><option value="CLARIFICATION_REQUESTED">Cần giải trình</option><option value="ALL">Tất cả</option></select><Button variant="outline" onClick={()=>setRev(x=>x+1)}><Filter/>Làm mới</Button></div>{error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}{busy?<div className="space-y-3"><Skeleton className="h-20"/><Skeleton className="h-20"/></div>:shown.length===0?<Card><CardContent className="py-12 text-center text-muted-foreground">Không có yêu cầu phù hợp.</CardContent></Card>:<><div className="hidden overflow-hidden rounded-xl border bg-card md:block"><Table><TableHeader><TableRow><TableHead>Nhân viên</TableHead><TableHead>Loại</TableHead><TableHead>Ngày</TableHead><TableHead>Trạng thái</TableHead><TableHead className="text-right">Thao tác</TableHead></TableRow></TableHeader><TableBody>{shown.map(r=><TableRow key={r._id}><TableCell>{names.get(r.employeeId)??'Nhân viên'}</TableCell><TableCell>{r.type==='OVERTIME'?'OT':'Công'}</TableCell><TableCell>{date(r.workDate)}</TableCell><TableCell><Status value={r.status}/></TableCell><TableCell className="text-right"><Button variant="outline" onClick={()=>setSelected(r)}>Xem chi tiết</Button></TableCell></TableRow>)}</TableBody></Table></div><div className="grid gap-3 md:hidden">{shown.map(r=><Card key={r._id}><CardHeader><div className="flex items-start justify-between gap-2"><CardTitle className="text-base">{names.get(r.employeeId)??'Nhân viên'}</CardTitle><Status value={r.status}/></div></CardHeader><CardContent className="space-y-3"><p className="text-sm"><strong>{r.type==='OVERTIME'?'OT':'Công'}</strong> · {date(r.workDate)}</p><p className="line-clamp-2 text-sm text-muted-foreground">{r.reason}</p><Button className="w-full" variant="outline" onClick={()=>setSelected(r)}>Xem chi tiết</Button></CardContent></Card>)}</div></>}{selected&&<DecisionDialog apiBase={apiBase} request={selected} employee={names.get(selected.employeeId)} onClose={()=>setSelected(null)} onDone={()=>{setSelected(null);setRev(x=>x+1)}}/>}</div>}
function Status({value}:{value:string}){return <Badge variant={value==='APPROVED'?'default':'secondary'}>{value==='PENDING'?'Chờ duyệt':value==='APPROVED'?'Đã duyệt':value==='REJECTED'?'Từ chối':'Cần giải trình'}</Badge>}
function DecisionDialog({apiBase,request,employee,onClose,onDone}:{apiBase:string;request:ManagerRequest;employee?:string;onClose:()=>void;onDone:()=>void}){const[reason,setReason]=useState(''),[sending,setSending]=useState(false),[error,setError]=useState('');const act=async(a:'approve'|'reject'|'request-clarification')=>{setSending(true);setError('');try{await decideManagerRequest(apiBase,request._id,a,{expectedVersion:request.version,reason:reason||undefined,approvedStart:request.requestedStart,approvedEnd:request.requestedEnd});onDone()}catch(e){setError(e instanceof Error?e.message:'Không thể xử lý yêu cầu.')}finally{setSending(false)}};return <Dialog open onOpenChange={onClose}><DialogContent className="h-dvh max-h-dvh w-screen max-w-none rounded-none sm:h-auto sm:max-h-[90vh] sm:w-full sm:max-w-xl sm:rounded-xl"><DialogHeader><DialogTitle>{request.type==='OVERTIME'?'Duyệt OT':'Duyệt công'} — {employee}</DialogTitle><DialogDescription>{date(request.workDate)} · phiên bản {request.version}</DialogDescription></DialogHeader><div className="space-y-4 overflow-y-auto p-6"><p className="rounded-lg bg-muted p-4 text-sm">{request.reason}</p>{request.type==='OVERTIME'&&<p className="text-sm"><Clock3 className="mr-1 inline size-4"/>{request.requestedStart?new Date(request.requestedStart).toLocaleString('vi-VN'):'—'} → {request.requestedEnd?new Date(request.requestedEnd).toLocaleString('vi-VN'):'—'}</p>}<label className="grid gap-2 text-sm font-medium">Lý do / nội dung giải trình<textarea className="min-h-24 rounded-lg border bg-background p-3" value={reason} onChange={e=>setReason(e.target.value)} placeholder="Bắt buộc khi từ chối hoặc yêu cầu giải trình (ít nhất 10 ký tự)"/></label>{error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}</div>{request.status==='PENDING'&&<div className="sticky bottom-0 grid gap-2 border-t bg-background p-4 sm:grid-cols-3"><Button disabled={sending} onClick={()=>act('approve')}><Check/>Duyệt</Button><Button disabled={sending||reason.trim().length<10} variant="outline" onClick={()=>act('request-clarification')}><MessageSquareText/>Giải trình</Button><Button disabled={sending||reason.trim().length<10} variant="destructive" onClick={()=>act('reject')}><X/>Từ chối</Button></div>}</DialogContent></Dialog>}
