import { useEffect,useState } from 'react';
import { Badge } from '@/components/badge';
import { Button } from '@/components/button';
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from '@/components/dialog';
import { Skeleton } from '@/components/skeleton';
import type { Department } from '@/services/hrService';
import { getShiftTemplateById,type ShiftTemplate } from '@/services/shift-template.service';
const DAYS:Record<number,string>={1:'T2',2:'T3',3:'T4',4:'T5',5:'T6',6:'T7',7:'CN'};
export function ShiftTemplateDetailDialog({apiBase,templateId,departments,open,onOpenChange}:{apiBase:string;templateId:string|null;departments:Department[];open:boolean;onOpenChange:(open:boolean)=>void}){const[row,setRow]=useState<ShiftTemplate|null>(null),[loading,setLoading]=useState(false);useEffect(()=>{if(!open||!templateId)return;setLoading(true);getShiftTemplateById(apiBase,templateId).then(setRow).finally(()=>setLoading(false))},[apiBase,open,templateId]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-2xl"><DialogHeader className="border-b pr-16"><DialogTitle>Chi tiết ca làm việc</DialogTitle><DialogDescription>Phạm vi, lịch lặp và thời gian áp dụng.</DialogDescription></DialogHeader>{loading||!row?<div className="space-y-3 px-6 pb-6"><Skeleton className="h-10"/><Skeleton className="h-10"/></div>:<dl className="grid gap-5 px-6 pb-4 sm:grid-cols-2"><Item label="Tên ca" value={row.name||'Chưa đặt tên'}/><Item label="Phạm vi" value={row.scope==='ORGANIZATION'?'Toàn bộ công ty':departments.find(d=>d._id===row.departmentId)?.name||'Phòng ban không tồn tại'}/><Item label="Ngày lặp" value={row.weekdays.map(d=>DAYS[d]).join(', ')}/><Item label="Hiệu lực" value={`${row.effectiveFrom} → ${row.effectiveTo||'Không giới hạn'}`}/><Item label="Giờ làm" value={`${row.startTime}–${row.endTime}`}/><Item label="Nghỉ / thời gian cho phép đi trễ" value={`${row.breakMinutes} / ${row.gracePeriodMinutes} phút`}/><div><dt className="text-xs text-muted-foreground">Trạng thái</dt><dd className="mt-1"><Badge variant="secondary" className={row.active?'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300':'bg-slate-100 text-slate-600 dark:bg-slate-900 dark:text-slate-300'}>{row.active?'Đang hoạt động':'Ngưng hoạt động'}</Badge></dd></div></dl>}<div className="mx-6 mb-6 flex justify-end border-t pt-5"><Button variant="outline" onClick={()=>onOpenChange(false)}>Đóng</Button></div></DialogContent></Dialog>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
