import { useEffect, useMemo, useState } from 'react';
import { CalendarCheck2, CheckCircle2, Eye, FileClock, RefreshCw, ShieldCheck, WandSparkles } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/alert';
import { Badge } from '@/components/badge';
import { Button } from '@/components/button';
import { Card, CardContent } from '@/components/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/dialog';
import { FormError } from '@/components/form/FormError';
import { FormLabel } from '@/components/form/FormLabel';
import { Input } from '@/components/input';
import { Skeleton } from '@/components/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/table';
import { toast } from '@/components/toast';
import { getEmployees } from '@/services/hrService';
import {
  applyLeaveRequest,
  listEmployeeDayOverrides,
  listHrLeaveRequests,
  rebuildDayClassifications,
  type EmployeeDayOverride,
  type LeaveRequest,
  type LeaveStatus,
} from '@/services/leave.service';
import { formatLeaveDate, leaveDays, leaveError, LeaveStatusBadge, leaveTypeLabel } from './leave-ui';
import { LeaveDetail } from './EmployeeLeaveScreen';

const today=()=>new Date().toISOString().slice(0,10);
const firstOfMonth=()=>`${today().slice(0,7)}-01`;

export function HrLeaveScreen({apiBase}:{apiBase:string}){
  const [rows,setRows]=useState<LeaveRequest[]>([]),[employees,setEmployees]=useState<Array<{userId:string;employeeCode:string;fullName?:string|null}>>([]),[status,setStatus]=useState<'all'|LeaveStatus>('APPROVED'),[employeeId,setEmployeeId]=useState(''),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[detail,setDetail]=useState<LeaveRequest|null>(null),[applying,setApplying]=useState<LeaveRequest|null>(null),[busy,setBusy]=useState(false),[rev,setRev]=useState(0);
  const [result,setResult]=useState<{request:LeaveRequest;overrides:EmployeeDayOverride[]}|null>(null),[rebuildOpen,setRebuildOpen]=useState(false),[from,setFrom]=useState(firstOfMonth()),[to,setTo]=useState(today()),[rebuildEmployee,setRebuildEmployee]=useState(''),[formError,setFormError]=useState('');
  useEffect(()=>{let cancelled=false;setLoading(true);setError('');Promise.all([listHrLeaveRequests(apiBase,status==='all'?undefined:status),getEmployees(apiBase,{})]).then(([requests,people])=>{if(cancelled)return;setRows(requests);setEmployees(people.employees)}).catch(e=>!cancelled&&setError(leaveError(e))).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[apiBase,rev,status]);
  const employeeMap=useMemo(()=>new Map(employees.map(e=>[e.userId,e])),[employees]);
  const visible=useMemo(()=>{const key=query.trim().toLocaleLowerCase('vi');return rows.filter(row=>(!employeeId||row.employeeId===employeeId)&&(!key||[employeeMap.get(row.employeeId)?.fullName,employeeMap.get(row.employeeId)?.employeeCode,row.reason,row.startDate,row.endDate].some(value=>String(value||'').toLocaleLowerCase('vi').includes(key))))},[employeeId,employeeMap,query,rows]);
  const approved=rows.filter(row=>row.status==='APPROVED').length,applied=rows.filter(row=>row.status==='HR_APPLIED').length;
  async function confirmApply(){if(!applying)return;setBusy(true);setFormError('');try{const request=await applyLeaveRequest(apiBase,applying._id);const overrides=await listEmployeeDayOverrides(apiBase,{employeeId:applying.employeeId,from:applying.startDate,to:applying.endDate});setResult({request,overrides:overrides.filter(item=>item.leaveRequestId===applying._id)});setApplying(null);setRev(x=>x+1);toast.success('Đã áp dụng nghỉ phép',`${leaveDays(applying)} ngày đã được chuyển thành phân loại ngày nghỉ.`)}catch(e){setFormError(leaveError(e))}finally{setBusy(false)}}
  async function rebuild(){if(to<from){setFormError('Ngày kết thúc phải từ ngày bắt đầu trở đi.');return}setBusy(true);setFormError('');try{const value=await rebuildDayClassifications(apiBase,{from,to,employeeId:rebuildEmployee||undefined});toast.success('Đã phân loại lại ngày công',`${value.updatedCount}/${value.scannedCount} bản ghi đã được cập nhật.`);setRebuildOpen(false)}catch(e){setFormError(leaveError(e))}finally{setBusy(false)}}
  return <div className="space-y-6">
    <header className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Áp dụng nghỉ phép</h1><p className="mt-2 text-sm text-muted-foreground">Chuyển yêu cầu đã duyệt thành phân loại ngày công và EmployeeDayOverride.</p></div><Button variant="outline" onClick={()=>{setFormError('');setRebuildOpen(true)}}><WandSparkles/>Phân loại lại ngày công</Button></header>
    <div className="grid gap-3 sm:grid-cols-3"><Summary icon={FileClock} label="Chờ HR áp dụng" value={approved}/><Summary icon={CheckCircle2} label="Đã áp dụng" value={applied}/><Summary icon={ShieldCheck} label="Đang hiển thị" value={visible.length}/></div>
    {error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
    <div className="overflow-hidden rounded-xl border bg-card"><div className="grid gap-4 border-b p-4 sm:grid-cols-2 lg:grid-cols-[1fr_220px_220px_auto] lg:items-end sm:p-6"><FormLabel className="space-y-2"><span>Tìm kiếm</span><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nhân viên, lý do hoặc ngày…"/></FormLabel><FormLabel className="space-y-2"><span>Nhân viên</span><select className="h-10 rounded-lg border bg-background px-3" value={employeeId} onChange={e=>setEmployeeId(e.target.value)}><option value="">Tất cả nhân viên</option>{employees.map(e=><option key={e.userId} value={e.userId}>{e.fullName||e.employeeCode}</option>)}</select></FormLabel><FormLabel className="space-y-2"><span>Trạng thái</span><select className="h-10 rounded-lg border bg-background px-3" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="APPROVED">Chờ HR áp dụng</option><option value="HR_APPLIED">Đã áp dụng</option><option value="REJECTED">Đã từ chối</option><option value="all">Tất cả trạng thái</option></select></FormLabel><Button size="icon" variant="outline" aria-label="Làm mới yêu cầu nghỉ" onClick={()=>setRev(x=>x+1)}><RefreshCw/></Button></div>
      {loading?<div className="space-y-3 p-6" role="status">{[1,2,3,4].map(i=><Skeleton key={i} className="h-14"/>)}</div>:!visible.length?<div className="p-14 text-center text-muted-foreground"><CalendarCheck2 className="mx-auto mb-3 size-10"/><p className="font-medium text-foreground">Không có yêu cầu phù hợp</p><p className="mt-1 text-sm">Thay đổi bộ lọc hoặc chờ Manager duyệt yêu cầu mới.</p></div>:<><div className="hidden overflow-x-auto md:block"><Table className="min-w-[1000px]"><TableHeader><TableRow><TableHead className="pl-6">Nhân viên</TableHead><TableHead>Khoảng nghỉ</TableHead><TableHead>Loại nghỉ</TableHead><TableHead>Lý do</TableHead><TableHead>Trạng thái</TableHead><TableHead className="pr-6 text-right">Thao tác</TableHead></TableRow></TableHeader><TableBody>{visible.map(row=>{const employee=employeeMap.get(row.employeeId);return <TableRow key={row._id}><TableCell className="pl-6"><strong>{employee?.fullName||row.employeeId}</strong><small className="block text-muted-foreground">{employee?.employeeCode}</small></TableCell><TableCell>{formatLeaveDate(row.startDate)} → {formatLeaveDate(row.endDate)}<small className="block text-muted-foreground">{leaveDays(row)} ngày</small></TableCell><TableCell><Badge variant="outline">{leaveTypeLabel[row.leaveType]}</Badge></TableCell><TableCell className="max-w-60 truncate">{row.reason}</TableCell><TableCell><LeaveStatusBadge status={row.status}/></TableCell><TableCell className="pr-6"><div className="flex justify-end gap-2"><Button size="icon" variant="ghost" aria-label="Xem yêu cầu nghỉ" onClick={()=>setDetail(row)}><Eye/></Button>{row.status==='APPROVED'&&<Button size="sm" onClick={()=>{setFormError('');setApplying(row)}}><CalendarCheck2/>Áp dụng</Button>}</div></TableCell></TableRow>})}</TableBody></Table></div><div className="grid gap-3 p-4 md:hidden">{visible.map(row=>{const employee=employeeMap.get(row.employeeId);return <Card key={row._id} className="shadow-none"><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-2"><div><strong>{employee?.fullName||row.employeeId}</strong><small className="block text-muted-foreground">{employee?.employeeCode}</small></div><LeaveStatusBadge status={row.status}/></div><p className="text-sm">{formatLeaveDate(row.startDate)} → {formatLeaveDate(row.endDate)} · {leaveDays(row)} ngày</p><p className="line-clamp-2 text-sm text-muted-foreground">{row.reason}</p><div className="flex gap-2"><Button size="sm" variant="outline" onClick={()=>setDetail(row)}>Chi tiết</Button>{row.status==='APPROVED'&&<Button size="sm" onClick={()=>setApplying(row)}>Áp dụng</Button>}</div></CardContent></Card>})}</div></>}
    </div>
    <LeaveDetail row={detail} onClose={()=>setDetail(null)}/>
    <Dialog open={!!applying} onOpenChange={next=>!next&&!busy&&setApplying(null)}><DialogContent className="max-w-lg"><DialogHeader className="border-b pr-16"><DialogTitle>Xác nhận áp dụng nghỉ phép?</DialogTitle><DialogDescription>Thao tác tạo một EmployeeDayOverride cho từng ngày và cập nhật phân loại ngày công trong cùng transaction.</DialogDescription></DialogHeader><div className="px-6"><FormError message={formError}/>{applying&&<div className="rounded-lg bg-muted p-4 text-sm"><p className="font-medium">{employeeMap.get(applying.employeeId)?.fullName||applying.employeeId}</p><p className="mt-1 text-muted-foreground">{formatLeaveDate(applying.startDate)} → {formatLeaveDate(applying.endDate)} · {leaveDays(applying)} ngày · {leaveTypeLabel[applying.leaveType]}</p></div>}</div><div className="mx-6 mb-6 flex justify-end gap-3 border-t pt-5"><Button variant="outline" disabled={busy} onClick={()=>setApplying(null)}>Hủy</Button><Button disabled={busy} onClick={confirmApply}>{busy?'Đang áp dụng…':'Xác nhận áp dụng'}</Button></div></DialogContent></Dialog>
    <Dialog open={!!result} onOpenChange={next=>!next&&setResult(null)}><DialogContent className="max-w-2xl"><DialogHeader className="border-b pr-16"><DialogTitle>Áp dụng thành công</DialogTitle><DialogDescription>Đã tạo {result?.overrides.length||0} phân loại ngày nghỉ, trạng thái yêu cầu là HR_APPLIED.</DialogDescription></DialogHeader><div className="max-h-[45vh] overflow-auto px-6"><div className="divide-y rounded-lg border">{result?.overrides.map(item=><div key={item._id||item.date} className="flex items-center justify-between gap-4 p-3 text-sm"><span className="font-medium">{formatLeaveDate(item.date)}</span><Badge variant="outline">{leaveTypeLabel[item.type]}</Badge></div>)}{result&&!result.overrides.length&&<p className="p-5 text-center text-sm text-muted-foreground">Không tải được danh sách override để đối soát.</p>}</div></div><div className="mx-6 mb-6 flex justify-end border-t pt-5"><Button onClick={()=>setResult(null)}>Hoàn tất</Button></div></DialogContent></Dialog>
    <Dialog open={rebuildOpen} onOpenChange={next=>!busy&&setRebuildOpen(next)}><DialogContent className="max-w-xl"><DialogHeader className="border-b pr-16"><DialogTitle>Phân loại lại ngày công</DialogTitle><DialogDescription>Áp dụng độ ưu tiên: nghỉ phép → ngày lễ → ngày nghỉ tuần → lịch làm việc và attendance.</DialogDescription></DialogHeader><div className="px-6"><FormError message={formError}/></div><div className="grid gap-4 px-6 sm:grid-cols-2"><FormLabel className="space-y-2"><span>Từ ngày</span><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></FormLabel><FormLabel className="space-y-2"><span>Đến ngày</span><Input type="date" min={from} value={to} onChange={e=>setTo(e.target.value)}/></FormLabel><FormLabel className="space-y-2 sm:col-span-2"><span>Nhân viên</span><select className="h-10 w-full rounded-lg border bg-background px-3" value={rebuildEmployee} onChange={e=>setRebuildEmployee(e.target.value)}><option value="">Tất cả nhân viên</option>{employees.map(e=><option key={e.userId} value={e.userId}>{e.fullName||e.employeeCode}</option>)}</select></FormLabel></div><div className="mx-6 mb-6 flex justify-end gap-3 border-t pt-5"><Button variant="outline" disabled={busy} onClick={()=>setRebuildOpen(false)}>Hủy</Button><Button disabled={busy} onClick={rebuild}>{busy?'Đang phân loại…':'Chạy phân loại'}</Button></div></DialogContent></Dialog>
  </div>
}

function Summary({icon:Icon,label,value}:{icon:typeof FileClock;label:string;value:number}){return <Card><CardContent className="flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-5"/></span><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div></CardContent></Card>}
