import { Badge } from '@/components/badge';
import type { LeaveRequest, LeaveStatus, LeaveType } from '@/services/leave.service';

export const leaveStatusLabel:Record<LeaveStatus,string>={PENDING_MANAGER:'Chờ quản lý',APPROVED:'Đã duyệt',REJECTED:'Đã từ chối',HR_APPLIED:'HR đã áp dụng'};
export const leaveTypeLabel:Record<LeaveType,string>={PAID_LEAVE:'Nghỉ hưởng lương',UNPAID_LEAVE:'Nghỉ không lương'};
export const formatLeaveDate=(value:string)=>new Intl.DateTimeFormat('vi-VN',{day:'2-digit',month:'2-digit',year:'numeric',timeZone:'UTC'}).format(new Date(`${value}T00:00:00Z`));
export const leaveDays=(row:Pick<LeaveRequest,'startDate'|'endDate'>)=>Math.round((Date.parse(`${row.endDate}T00:00:00Z`)-Date.parse(`${row.startDate}T00:00:00Z`))/86400000)+1;
export const leaveError=(error:unknown)=>{const code=(error as {code?:string})?.code;const messages:Record<string,string>={LEAVE_DATE_RANGE_INVALID:'Khoảng ngày nghỉ không hợp lệ.',LEAVE_RANGE_TOO_LARGE:'Khoảng nghỉ vượt quá giới hạn cho phép.',LEAVE_REQUEST_OVERLAP:'Khoảng ngày này giao với một yêu cầu nghỉ đang có hiệu lực.',EMPLOYEE_DEPARTMENT_REQUIRED:'Nhân viên chưa được phân công phòng ban.',LEAVE_SELF_APPROVAL_FORBIDDEN:'Quản lý không được tự duyệt yêu cầu của mình.',LEAVE_REQUEST_NOT_PENDING:'Yêu cầu này không còn ở trạng thái chờ duyệt.',LEAVE_REQUEST_ALREADY_DECIDED:'Yêu cầu đã được quản lý khác xử lý.',DEPARTMENT_SCOPE_VIOLATION:'Yêu cầu không thuộc phòng ban bạn quản lý.',LEAVE_SELF_APPLY_FORBIDDEN:'HR không được tự áp dụng yêu cầu nghỉ của mình.',LEAVE_REQUEST_NOT_APPROVED:'Chỉ yêu cầu đã được Manager duyệt mới có thể áp dụng.',LEAVE_REQUEST_ALREADY_APPLIED:'Yêu cầu đã được HR khác áp dụng.',LEAVE_DAY_ALREADY_OVERRIDDEN:'Một hoặc nhiều ngày đã có phân loại nghỉ khác.',CLASSIFICATION_DATE_RANGE_INVALID:'Khoảng ngày phân loại không hợp lệ.',CLASSIFICATION_RANGE_TOO_LARGE:'Chỉ được phân loại tối đa 366 ngày mỗi lần.'};return(code&&messages[code])||(error instanceof Error?error.message:'Không thể thực hiện thao tác.')};
export function LeaveStatusBadge({status}:{status:LeaveStatus}){const classes:Record<LeaveStatus,string>={PENDING_MANAGER:'bg-amber-50 text-amber-700 dark:bg-amber-950 dark:text-amber-300',APPROVED:'bg-blue-50 text-blue-700 dark:bg-blue-950 dark:text-blue-300',REJECTED:'bg-rose-50 text-rose-700 dark:bg-rose-950 dark:text-rose-300',HR_APPLIED:'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300'};return <Badge variant="secondary" className={classes[status]}>{leaveStatusLabel[status]}</Badge>}
