import { useEffect, useMemo, useState } from 'react';
import { Check, Clock3, Eye, FileCheck2, Search, X } from 'lucide-react';
import { Alert, AlertDescription } from '@/components/alert';
import { Badge } from '@/components/badge';
import { Button } from '@/components/button';
import { Card, CardContent } from '@/components/card';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/dialog';
import { FormError } from '@/components/form/FormError';
import { FormLabel } from '@/components/form/FormLabel';
import { Input } from '@/components/input';
import { Skeleton } from '@/components/skeleton';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/table';
import { toast } from '@/components/toast';
import { approveLeaveRequest, listManagerLeaveRequests, rejectLeaveRequest, type LeaveRequest, type LeaveStatus } from '@/services/leave.service';
import { getManagerContext, getManagerEmployees, type ManagerEmployee } from '@/services/manager.service';
import { formatLeaveDate, leaveDays, leaveError, LeaveStatusBadge, leaveTypeLabel } from './leave-ui';
import { LeaveDetail } from './EmployeeLeaveScreen';

export function ManagerLeaveScreen({apiBase}:{apiBase:string}){
  const [rows,setRows]=useState<LeaveRequest[]>([]),[employees,setEmployees]=useState<ManagerEmployee[]>([]),[departments,setDepartments]=useState<Array<{id:string;code:string;name:string}>>([]),[departmentId,setDepartmentId]=useState(''),[status,setStatus]=useState<'all'|LeaveStatus>('PENDING_MANAGER'),[query,setQuery]=useState(''),[loading,setLoading]=useState(true),[error,setError]=useState(''),[detail,setDetail]=useState<LeaveRequest|null>(null),[decision,setDecision]=useState<{row:LeaveRequest;action:'approve'|'reject'}|null>(null),[reason,setReason]=useState(''),[formError,setFormError]=useState(''),[busy,setBusy]=useState(false),[rev,setRev]=useState(0);
  useEffect(()=>{let cancelled=false;setLoading(true);setError('');Promise.all([listManagerLeaveRequests(apiBase,status==='all'?undefined:status,departmentId||undefined),getManagerEmployees(apiBase,departmentId||undefined),getManagerContext(apiBase)]).then(([requests,people,context])=>{if(cancelled)return;setRows(requests);setEmployees(people);setDepartments(context.managedDepartments)}).catch(e=>!cancelled&&setError(leaveError(e))).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[apiBase,departmentId,rev,status]);
  const employeeMap=useMemo(()=>new Map(employees.map(e=>[e.userId,e])),[employees]);
  const visible=useMemo(()=>{const key=query.trim().toLocaleLowerCase('vi');return rows.filter(row=>!key||[employeeMap.get(row.employeeId)?.fullName,employeeMap.get(row.employeeId)?.employeeCode,row.reason,row.startDate,row.endDate].some(value=>String(value||'').toLocaleLowerCase('vi').includes(key)))},[employeeMap,query,rows]);
  const pending=rows.filter(r=>r.status==='PENDING_MANAGER').length;
  function openDecision(row:LeaveRequest,action:'approve'|'reject'){setDecision({row,action});setReason('');setFormError('')}
  async function confirm(){if(!decision)return;if(decision.action==='reject'&&reason.trim().length<3){setFormError('Lý do từ chối phải có ít nhất 3 ký tự.');return}setBusy(true);try{if(decision.action==='approve')await approveLeaveRequest(apiBase,decision.row._id);else await rejectLeaveRequest(apiBase,decision.row._id,reason.trim());toast.success(decision.action==='approve'?'Đã duyệt yêu cầu nghỉ.':'Đã từ chối yêu cầu nghỉ.');setDecision(null);setRev(x=>x+1)}catch(e){setFormError(leaveError(e))}finally{setBusy(false)}}
  return <div className="space-y-6"><header><h1 className="text-2xl font-semibold tracking-tight sm:text-3xl">Duyệt nghỉ phép</h1><p className="mt-2 text-sm text-muted-foreground">Xem xét LeaveRequest của nhân viên thuộc phòng ban bạn quản lý.</p></header>
    <div className="grid gap-3 sm:grid-cols-3"><Summary icon={Clock3} label="Đang chờ duyệt" value={pending}/><Summary icon={FileCheck2} label="Đang hiển thị" value={visible.length}/><Summary icon={Check} label="Phòng ban quản lý" value={departments.length}/></div>
    {error&&<Alert variant="destructive"><AlertDescription>{error}</AlertDescription></Alert>}
    <div className="overflow-hidden rounded-xl border bg-card"><div className="grid gap-4 border-b p-4 sm:grid-cols-2 lg:grid-cols-[1fr_220px_220px] lg:items-end sm:p-6"><FormLabel className="space-y-2"><span>Tìm kiếm</span><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"/><Input className="pl-9" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Nhân viên, lý do hoặc ngày…"/></div></FormLabel><FormLabel className="space-y-2"><span>Phòng ban</span><select className="h-10 rounded-lg border bg-background px-3" value={departmentId} onChange={e=>setDepartmentId(e.target.value)}><option value="">Tất cả phòng ban</option>{departments.map(d=><option key={d.id} value={d.id}>{d.code} — {d.name}</option>)}</select></FormLabel><FormLabel className="space-y-2"><span>Trạng thái</span><select className="h-10 rounded-lg border bg-background px-3" value={status} onChange={e=>setStatus(e.target.value as typeof status)}><option value="all">Tất cả trạng thái</option><option value="PENDING_MANAGER">Chờ quản lý</option><option value="APPROVED">Đã duyệt</option><option value="REJECTED">Đã từ chối</option><option value="HR_APPLIED">HR đã áp dụng</option></select></FormLabel></div>
      {loading?<div className="space-y-3 p-6">{[1,2,3,4].map(i=><Skeleton key={i} className="h-14"/>)}</div>:!visible.length?<div className="p-14 text-center text-muted-foreground"><FileCheck2 className="mx-auto mb-3 size-10"/><p className="font-medium text-foreground">Không có yêu cầu cần xử lý</p><p className="mt-1 text-sm">Queue được giới hạn theo department scope của bạn.</p></div>:<><div className="hidden overflow-x-auto md:block"><Table className="min-w-[1000px]"><TableHeader><TableRow><TableHead className="pl-6">Nhân viên</TableHead><TableHead>Khoảng nghỉ</TableHead><TableHead>Loại nghỉ</TableHead><TableHead>Lý do</TableHead><TableHead>Trạng thái</TableHead><TableHead className="pr-6 text-right">Thao tác</TableHead></TableRow></TableHeader><TableBody>{visible.map(row=>{const employee=employeeMap.get(row.employeeId);return <TableRow key={row._id}><TableCell className="pl-6"><strong>{employee?.fullName||row.employeeId}</strong><small className="block text-muted-foreground">{employee?.employeeCode}</small></TableCell><TableCell>{formatLeaveDate(row.startDate)} → {formatLeaveDate(row.endDate)}<small className="block text-muted-foreground">{leaveDays(row)} ngày</small></TableCell><TableCell><Badge variant="outline">{leaveTypeLabel[row.leaveType]}</Badge></TableCell><TableCell className="max-w-60 truncate">{row.reason}</TableCell><TableCell><LeaveStatusBadge status={row.status}/></TableCell><TableCell className="pr-6"><div className="flex justify-end gap-1"><Button size="icon" variant="ghost" aria-label="Xem yêu cầu" onClick={()=>setDetail(row)}><Eye/></Button>{row.status==='PENDING_MANAGER'&&<><Button size="sm" onClick={()=>openDecision(row,'approve')}><Check/>Duyệt</Button><Button size="sm" variant="outline" onClick={()=>openDecision(row,'reject')}><X/>Từ chối</Button></>}</div></TableCell></TableRow>})}</TableBody></Table></div><div className="grid gap-3 p-4 md:hidden">{visible.map(row=>{const employee=employeeMap.get(row.employeeId);return <Card key={row._id} className="shadow-none"><CardContent className="space-y-3 p-4"><div className="flex items-start justify-between gap-2"><div><strong>{employee?.fullName||row.employeeId}</strong><small className="block text-muted-foreground">{employee?.employeeCode}</small></div><LeaveStatusBadge status={row.status}/></div><p className="text-sm">{formatLeaveDate(row.startDate)} → {formatLeaveDate(row.endDate)} · {leaveDays(row)} ngày</p><p className="line-clamp-2 text-sm text-muted-foreground">{row.reason}</p><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={()=>setDetail(row)}>Chi tiết</Button>{row.status==='PENDING_MANAGER'&&<><Button size="sm" onClick={()=>openDecision(row,'approve')}>Duyệt</Button><Button size="sm" variant="outline" onClick={()=>openDecision(row,'reject')}>Từ chối</Button></>}</div></CardContent></Card>})}</div></>}
    </div><LeaveDetail row={detail} onClose={()=>setDetail(null)}/>
    <Dialog open={!!decision} onOpenChange={next=>!next&&!busy&&setDecision(null)}><DialogContent className="max-w-lg"><DialogHeader className="border-b pr-16"><DialogTitle>{decision?.action==='approve'?'Duyệt yêu cầu nghỉ?':'Từ chối yêu cầu nghỉ?'}</DialogTitle><DialogDescription>{decision?.row&&`${formatLeaveDate(decision.row.startDate)} → ${formatLeaveDate(decision.row.endDate)} · ${leaveDays(decision.row)} ngày`}</DialogDescription></DialogHeader><div className="px-6"><FormError message={formError}/></div>{decision?.action==='reject'&&<FormLabel className="mx-6 space-y-2"><span>Lý do từ chối <span className="text-destructive">*</span></span><textarea className="min-h-24 rounded-lg border bg-background p-3 text-sm" value={reason} onChange={e=>setReason(e.target.value)} maxLength={1000} placeholder="Nhập lý do để nhân viên biết…"/></FormLabel>}<div className="mx-6 mb-6 flex justify-end gap-3 border-t pt-5"><Button variant="outline" disabled={busy} onClick={()=>setDecision(null)}>Hủy</Button><Button variant={decision?.action==='reject'?'destructive':'default'} disabled={busy} onClick={confirm}>{busy?'Đang xử lý…':decision?.action==='approve'?'Xác nhận duyệt':'Xác nhận từ chối'}</Button></div></DialogContent></Dialog>
  </div>
}
function Summary({icon:Icon,label,value}:{icon:typeof Clock3;label:string;value:number}){return <Card><CardContent className="flex items-center gap-4 p-5"><span className="grid size-10 place-items-center rounded-lg bg-primary/10 text-primary"><Icon className="size-5"/></span><div><p className="text-sm text-muted-foreground">{label}</p><p className="text-2xl font-semibold">{value}</p></div></CardContent></Card>}
